#Server language is for servers messages and broadcasts
#Besides that, each player can have their own language messages that has the Minecraft client.
#If no language is found for a player in lang folder, en.yml will be used.

#Dont modifed the initial_server_bank_balance once has been set, it will be used to calculate inflation and deflation.
#To reset the server balance o change it, modify and then remove the database.

#database: sqlite, mysql
data_mode: "sqlite"
mysql:
  url: "host:port/database_name"
  username: "yourUsername"
  password: "yourPassword"

initial_server_bank_balance: 1000000000.0
debt_limit: 10000.0
loan_interest_per_day: 0.1666
savings_interest_per_day: 0.0833



