main: com.ar.askgaming.realisticeconomy.RealisticEconomy
name: RealisticEconomy
api-version: 1.21
version: 1.3
author: AMONLY
softdepend: [Vault, PlaceholderAPI]
commands:
  eco:
    description: Main command for RealisticEconomy
    usage: /eco <subcommand>
    aliases: [economy, money,bal,balance]
    permission: eco.user
  bank:
    description: Main command for RealisticEconomy bank
    usage: /bank <subcommand>
    permission: eco.user
  lottery:
    description: Main command for RealisticEconomy lotery
    usage: /lotery <subcommand>
    permission: eco.user
    aliases: [lot]
  tokens:
    description: Main command for RealisticEconomy tokens
    usage: /tokens <subcommand>
    permission: eco.user
    aliases: [token]
permissions:
  eco.admin:
    description: Allows access to all RealisticEconomy commands
    default: op