main: com.ar.askgaming.realisticeconomy.Main
name: RealisticEconomy
api-version: 1.21
version: 1
author: AMONLY
depend: [Vault]
commands:
  eco:
    description: Main command for RealisticEconomy
    usage: /eco <subcommand>
    aliases: [economy]
    permission: eco.user
permissions:
  eco.admin:
    description: Allows access to all RealisticEconomy commands
    default: op