main: com.ar.askgaming.realisticeconomy.RealisticEconomy
name: RealisticEconomy
api-version: 1.21
version: 1
author: AMONLY
soft-depend: [Vault]
commands:
  eco:
    description: Main command for RealisticEconomy
    usage: /eco <subcommand>
    aliases: [economy]
    permission: eco.user
  bank:
    description: Main command for RealisticEconomy bank
    usage: /bank <subcommand>
    permission: eco.user
  lotery:
    description: Main command for RealisticEconomy lotery
    usage: /lotery <subcommand>
    permission: eco.user
  reauction:
    description: Main command for RealisticEconomy reauction
    usage: /reauction <subcommand>
    permission: eco.user
  tokens:
    description: Main command for RealisticEconomy tokens
    usage: /tokens <subcommand>
    permission: eco.user
permissions:
  eco.admin:
    description: Allows access to all RealisticEconomy commands
    default: op